name: Release Drafter
on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: Update Release Notes
    uses: plamentotev/.github/.github/workflows/release-drafter.yml@master
    with:
      config-name: release-drafter-local.yml
